#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "provide VPC_ID"
else
    export VPC_ID="$1"
fi
if [ -z "$2" ]; then
    echo "provide IGW_ID"
else
    export IGW_ID="$2"
fi
if [ -z "$3" ]; then
    echo "provide SUBNET_ID"
else
    export SUBNET_ID="$3"
fi


aws ec2 detach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

aws ec2 delete-internet-gateway \
--internet-gateway-id $IGW_ID

aws ec2 delete-subnet --subnet-id $SUBNET_ID

aws ec2 delete-vpc --vpc-id $VPC_ID